services:
  crafty:
    container_name: crafty_controller
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: unless-stopped
    environment:
        - TZ=America/Sao_Paulo
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./crafty_data/backups:/crafty/backups
        - ./crafty_data/logs:/crafty/logs
        - ./crafty_data/servers:/crafty/servers
        - ./crafty_data/config:/crafty/app/config
        - ./crafty_data/import:/crafty/import
    networks:
      - minecraft_net

  playit:
    container_name: playit_agent
    image: ghcr.io/playit-cloud/playit-agent:0.16
    restart: unless-stopped
    environment:
      - SECRET_KEY=${PLAYIT_GG_SECRET_KEY}
    depends_on:
      - crafty
    volumes:
      - ./playit_data:/config
    network_mode: host

networks:
  minecraft_net:
    driver: bridge